blueprint:
  name: Action On Motion Detection
  description: For Doing Things When there is motion.
  domain: automation
  author: RSZEE
  input: 
    motion_sensor:
      name: Motion Sensor 
      selector: 
          entity:
            filter:
              - domain: binary_sensor
                device_class: motion
    action:
      name: Action
      selector:
        action: {}
mode: single
trigger:
  - platform: state
    entity_id: !input motion_sensor 
    from: "off"
    to: "on"
condition: []
action: !input action
