blueprint:
  name: Timed Notification
  description: For sending Notifications at a time.
  domain: automation
  author: RSZEE
  input:
    time:
      name: Time
      description: What time to send the notification. Format = HR:M:S
    text:
      name: Message
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app
  source_url: https://github.com/RSZEE/Home-Assistant-Blueprints/edit/main/timed_notification.yaml
mode: single
trigger:
  - platform: time
    at: !input time
condition: []
action:
  - alias: Notify someone
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    message: !input text
